version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=codrr_db
      - MYSQL_ROOT_USER=ucodrr
      - MYSQL_USER=ucodrr
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_PASSWORD=secret
    ports:
      - '3312:3306'
    volumes:
     - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local